import Navbar from '@/app/components/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'




const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Hossam || front end',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
   
  return (
    <html lang="en" className='scroll-smooth' style={{scrollBehavior:'smooth'}}>
      <body className={inter.className}>
      <Navbar/>
      {children}
      </body>
    </html>
  )
}
