"use client"
import Navbar from '@/app/components/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import { useEffect } from "react";
import AOS from "aos";
import "aos/dist/aos.css";




const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Hossam || front end',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
   useEffect(() => {
    AOS.init({
      easing: "ease-out-cubic",
      once: true,
      offset: 10,
    });
  }, []);
  return (
    <html lang="en" className='scroll-smooth' style={{scrollBehavior:'smooth'}}>
      <body className={inter.className}>
      <Navbar/>
      {children}
      </body>
    </html>
  )
}
